version: 2

updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
  - package-ecosystem: cargo
    directory: '/'
    # Handle updates for crates from https://github.com/paritytech/polkadot-sdk manually.
    ignore:
      - dependency-name: 'sc-*'
      - dependency-name: 'sp-*'
      - dependency-name: 'frame-*'
      - dependency-name: 'pallet-*'
      - dependency-name: 'substrate-*'
      - dependency-name: 'polkadot-*'
      - dependency-name: 'cumulus-*'
      - dependency-name: 'assets-*'
      - dependency-name: 'xcm-*'
    schedule:
      interval: 'daily'
