[settings]
timeout = 1000

[relaychain]
chain = "rococo-local"
default_command = "/Users/ozgunozerk/Developer/openzeppelin-template/generic-template/bin-v1.6.0/polkadot"
settings = {}


[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 1000
addToGenesis = true
cumulus_based = true
chain = "dev"

[[parachains.collators]]
name = "collator01"
command = "/Users/ozgunozerk/Developer/openzeppelin-template/generic-template/target/release/parachain-template-node"
ws_port = 9933
rpc_port = 8833
args = ["--rpc-max-connections 10000"]
