:source-highlighter: highlight.js
:highlightjs-languages: rust
:github-icon: pass:[<svg class="icon"><use href="#github-icon"/></svg>]

= pallet_treasury

Branch/Release: `release-polkadot-v1.7.0`

== Purpose

The Treasury pallet provides a “pot” of funds that can be managed by stakeholders in the system and a structure for making spending proposals from this pot.

== Config link:https://github.com/paritytech/polkadot-sdk/blob/release-polkadot-v1.7.0/substrate/frame/treasury/src/lib.rs#L202[{github-icon},role=heading-link]

* Pallet-specific configs
** `OnSlash` -- Handler for the unbalanced decrease when slashing for a rejected proposal or bounty.
** `ProposalBond` --  Fraction of a proposal's value that should be bonded in order to place the proposal. An accepted proposal gets these back. A rejected proposal does not.
** `ProposalBondMinimum` -- Minimum amount of funds that should be placed in a deposit for making a proposal.
** `ProposalBondMaximum` -- Maximum amount of funds that should be placed in a deposit for making a proposal.
** `SpendPeriod` -- Period between successive spends. "Spend" means, treasury spending money to a proposal. `SpendPeriod` determines how often the treasury pallet distributes the assets to the proposals.
** `Burn` -- Percentage of spare funds (if any) that are burnt per spend period.
** `BurnDestination` -- Handler for the unbalanced decrease when treasury funds are burned.
** `SpendFunds` -- Runtime hooks to external pallet using treasury to compute spend funds.
** `MaxApprovals` -- The maximum number of approvals that can wait in the spending queue. NOTE: This parameter is also used within the Bounties Pallet extension if enabled.
** `AssetKind` -- Type parameter representing the asset kinds to be spent from the treasury.
** `Beneficiary` -- Type parameter used to identify the beneficiaries eligible to receive treasury spends.
** `BeneficiaryLookup` -- Converting trait to take a source type and convert to [`Self::Beneficiary`].
** `Paymaster` -- Type for processing spends of [Self::AssetKind] in favor of [`Self::Beneficiary`].
** `BalanceConverter` -- Type for converting the balance of an [Self::AssetKind] to the balance of the native asset, solely for the purpose of asserting the result against the maximum allowed spend amount of the [`Self::SpendOrigin`].
** `PayoutPeriod` -- The period during which an approved treasury spend has to be claimed by the beneficiary of the proposal.

* Pallet-specific origins:
** `ApproveOrigin` -- Origin from which approvals must come.
** `RejectOrigin` -- Origin from which rejections must come.
** `SpendOrigin` -- The origin required for approving spends from the treasury outside of the proposal process. The `Success` value is the maximum amount in a native asset that this origin is allowed to spend at a time.

* Common configs
** `Currency` -- The staking balance.
** `RuntimeEvent` -- The overarching event type.
** `PalletId` -- The treasury's pallet id, used for deriving its sovereign account ID.
** `WeightInfo` -- Weight information for extrinsics in this pallet.
** `BenchmarkHelper` --  Helper type for benchmarks.

== Dispatchables link:https://github.com/paritytech/polkadot-sdk/blob/master/substrate/frame/treasury/src/lib.rs#L475[{github-icon},role=heading-link]

[.contract-item]
[[propose_spend]]
==== `[.contract-item-name]#++propose_spend++#`
[source,rust]
----
pub fn propose_spend(
    origin: OriginFor<T>,
	#[pallet::compact] value: BalanceOf<T, I>,
	beneficiary: AccountIdLookupOf<T>,
) -> DispatchResult
----
Put forward a suggestion for spending.

A deposit proportional to the value is reserved and slashed if the proposal is rejected. It is returned once the proposal is awarded.

WARNING: Deprecated! `propose_spend` will be removed in February 2024. Use `spend` instead.

**Params:**

* `origin: OriginFor<T>` -- caller (in this case, proposer) account. Must be signed.
* `value: BalanceOf<T, I>` -- proposed amount.
* `beneficiary: AccountIdLookupOf<T>` --  The destination account for the transfer.

**Errors:**

* `ErrorName` -- description of conditions, when this error happens

**Events:**

* `EventName(param1, param2)` -- description of event, if needed (they are often self-explanatory)

[.contract-item]
[[spend_local]]
==== `[.contract-item-name]#++spend_local++#`
[source,rust]
----
pub fn spend_local(
    origin: OriginFor<T>,
    #[pallet::compact] amount: BalanceOf<T, I>,
    beneficiary: AccountIdLookupOf<T>,
) -> DispatchResult
----
Propose and approve a spend of treasury funds.

NOTE: For record-keeping purposes, the proposer is deemed to be equivalent to the beneficiary.

**Params:**

* `origin: OriginFor<T>` -- Must be [`Config::SpendOrigin`] with the `Success` value being at least `amount`.
* `value: BalanceOf<T, I>` -- The amount to be transferred from the treasury to the `beneficiary`.
* `beneficiary: AccountIdLookupOf<T>` --  The destination account for the transfer.

**Errors:**

* `InsufficientPermission` -- if the amount to be spent is greater than what the dispatcher of this call is allowed to spend.
* `TooManyApprovals` -- when `MaxApprovals` limit is hit, and cannot add a new proposal to the storage.

**Events:**

* `SpendApproved(proposal_index, amount, beneficiary)`
