:source-highlighter: highlight.js
:highlightjs-languages: rust
:github-icon: pass:[<svg class="icon"><use href="#github-icon"/></svg>]

= Pallet Name link:https://github.com/paritytech/polkadot-sdk/blob/release-polkadot-v1.5.0/substrate/frame/message-queue/src/lib.rs[{github-icon},role=heading-link]

== Branch/Release: `release-polkadot-v{1.5.0}`

== Purpose

Flexible FRAME pallet for implementing message queues. This pallet can also initiate message processing using the `MessageProcessor` (see `Config`).

== Glossary

* _Term_ -- definition of the term

== Config
* `RuntimeEvent: From<Event<Self>> + IsType<<Self as frame_system::Config>::RuntimeEvent>` -- The overarching event type.
* `WeightInfo: WeightInfo;` -- Weight information for extrinsics in this pallet.
* `MessageProcessor: ProcessMessage` -- Processor for messages
* `Size: BaseArithmetic + Unsigned + Copy + Into<u32> + Member + Encode + Decode + MaxEncodedLen + TypeInfo + Default` -- Page/heap size type.
* `QueueChangeHandler: OnQueueChanged<<Self::MessageProcessor as ProcessMessage>::Origin>` -- Code to be called when a message queue changes - either with items introduced or removed.
* `QueuePausedQuery: QueuePausedQuery<<Self::MessageProcessor as ProcessMessage>::Origin>` -- Queried by the pallet to check whether a queue can be serviced.
* `type HeapSize: Get<Self::Size>` -- The size of the page; this also serves as the maximum message size which can be sent.
* `MaxStale: Get<u32>` -- The maximum number of stale pages (i.e. of overweight messages) allowed before culling can happen. Once there are more stale pages than this, then historical pages may be dropped, even if they contain unprocessed overweight messages.
* `ServiceWeight: Get<Option<Weight>>` -- The amount of weight (if any) which should be provided to the message queue for servicing enqueued items. This may be legitimately `None` in the case that you will call `ServiceQueues::service_queues` manually.


== Dispatchables

[.contract-item]
[[execute_overweight]]
==== `[.contract-item-name]#++execute_overweight++#`
[source,rust]
----
pub fn execute_overweight(
    origin: OriginFor<T>,
    message_origin: MessageOriginOf<T>,
    page: PageIndex,
    index: T::Size,
    weight_limit: Weight,
) -> DispatchResultWithPostInfo
----
Execute an overweight message.

Benchmark complexity considerations: O(index + weight_limit).

// four following blocks show how to make a highlight of some information. It will become a styled block

NOTE: Temporary processing errors will be propagated whereas permanent errors are treated
as success condition.

IMPORTANT: The `weight_limit` passed to this function does not affect the `weight_limit` set in other parts of the pallet.

**Params:**

* `param1: Type1` -- description of the parameter
* `origin: OriginFor<T>` -- Must be `Signed`.
* `message_origin: MessageOriginOf<T>` -- The origin from which the message to be executed arrived.
* `page: PageIndex` -- The page in the queue in which the message to be executed is sitting.
* `index: T::Size` -- The index into the queue of the message to be executed.
* `weight_limit: Weight` -- The maximum amount of weight allowed to be consumed in the execution
of the message. This weight limit does not affect other parts of the pallet, and it is only used for this call of `execute_overweight`.
**Errors:**

* `QueuePaused` -- if the queue that overweight message to be executed belongs to is paused.
* `NoPage` -- if the page that overweight message to be executed belongs to does not exist.
* `NoMessage` -- if the overweight message could not be found.
* `Queued` -- if the overweight message is already scheduled for future execution.
For a message to be labeled as overweight, the pallet must have previously attempted execution and
encountered failure due to insufficient weight for processing. Once marked as overweight, the message
is excluded from the queue for future execution. However, if the overweight message is unexpectedly
found in the queue of pending items, it indicates an anomaly. In such instances, an error is raised,
as the message should have been excluded from future execution attempts following its initial failure
due to being overweight.
* `AlreadyProcessed` -- if the overweight message is already processed.
* `InsufficientWeight` -- if the `weight_limit` is not enough to execute the overweight message.
* `TemporarilyUnprocessable` -- if the message processor `Yield`s execution of this message. This means, processing should be reattempted later.



**Events:**

* `EventName(param1, param2)` -- description of event, if needed (they are often self-explanatory)

== Important Mentions and FAQ's

Here you may put a freeform information about any aspect of the pallet.
