//! Runtime FHE configuration

// Bring the host interface into scope (this is the glue generated by #[runtime_interface])
use fhe_primitives::FheHost;
use pallet_fhe::{Config as FheConfig, FheOps};

use crate::{Runtime, RuntimeEvent};

pub struct FheOperator;

impl FheOps for FheOperator {
    #[inline]
    fn add(a: Vec<u8>, b: Vec<u8>) -> Vec<u8> {
        // Host call into node → runs fhe_add_impl(...)
        FheHost::add(a, b)
    }

    #[inline]
    fn sub(a: Vec<u8>, b: Vec<u8>) -> Vec<u8> {
        FheHost::sub(a, b)
    }

    #[inline]
    fn select(cond_ebool: Vec<u8>, x: Vec<u8>, y: Vec<u8>) -> Vec<u8> {
        FheHost::select(cond_ebool, x, y)
    }

    #[inline]
    fn try_increase(x: Vec<u8>, delta: Vec<u8>) -> (Vec<u8>, Vec<u8>) {
        FheHost::try_increase(x, delta)
    }

    #[inline]
    fn try_decrease(x: Vec<u8>, delta: Vec<u8>) -> (Vec<u8>, Vec<u8>) {
        FheHost::try_decrease(x, delta)
    }

    #[inline]
    fn as_zero() -> Vec<u8> {
        // Your host fn is named as_euint64_zero() in the example;
        // expose a trait method named as_zero() if you prefer.
        FheHost::as_euint64_zero()
    }

    #[inline]
    fn is_initialized(x: &Vec<u8>) -> bool {
        // Host takes ownership, so clone the small Vec<u8> handle.
        FheHost::is_initialized(x.clone())
    }

    // Optional ACL hooks; these are no-ops in your current host impl
    #[inline]
    fn allow_this(x: Vec<u8>) {
        FheHost::allow_this(x)
    }

    #[inline]
    fn allow_to(x: Vec<u8>, who_scale: Vec<u8>) {
        FheHost::allow_to(x, who_scale)
    }
}

impl pallet_fhe::Config for Runtime {
    type RuntimeEvent = RuntimeEvent;
    type RuntimeFhe = FheOperator;
    type WeightInfo = ();
}
