:source-highlighter: highlight.js
:highlightjs-languages: rust
:github-icon: pass:[<svg class="icon"><use href="#github-icon"/></svg>]

= Pallet Name

Branch/Release: `release-polkadot-v{x.x.x}`

== Purpose

== Source Code link:https://github.com[{github-icon},role=heading-link]

This is a freeform description of the tasks that this pallet fulfills

== Config

* Pallet-specific configs
** `ConfigType` -- description of config. Include the possible values if there is a set of them.
* Common configs
** `ConfigType` -- description of config, if needed

== Dispatchables

[.contract-item]
[[dispatchable_name]]
==== `[.contract-item-name]#++dispatchable_name++#`
[source,rust]
----
pub fn dispatchable_name(
    param1: Type1,
    param2: Type2
) -> DispatchResult
----
Freeform description of the dispatchable. It is good to include the important things that should be included there.

// four following blocks show how to make a highlight of some information. It will become a styled block

NOTE: This is how you state important information that should be acknowledged

IMPORTANT: This is how you put some information that should not be missed

WARNING: This thing is for important information missing which may lead to dangerous consequences

TIP: This is how you should give some useful advice

**Params:**

* `param1: Type1` -- description of the parameter

**Errors:**

* `ErrorName` -- description of conditions, when this error happens

**Events:**

* `EventName(param1, param2)` -- description of event, if needed (they are often self-explanatory)

== Important Mentions and FAQ's

Here you may put a freeform information about any aspect of the pallet.
