
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
imports_granularity = "Crate"
match_arm_blocks = false
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
use_small_heuristics = "Max"

# most of these are unstable, so we enable them
unstable_features = true


# wanted to enable below, but they are removing the documentation comments if there is an empty line in between
# wrap_comments = true
# format_code_in_doc_comments = true
