
//! Autogenerated weights for `pallet_xcm_weight_trader`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 42.0.0
//! DATE: 2024-11-03, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-172-31-15-118`, CPU: `Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// target/release/evm-template-node
// benchmark
// pallet
// --steps=50
// --repeat=20
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --json-file=benchmarking/results/results-pallet_xcm_weight_trader.json
// --pallet=pallet_xcm_weight_trader
// --chain=dev
// --output=benchmarking/new-benchmarks/pallet_xcm_weight_trader.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_xcm_weight_trader`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_xcm_weight_trader::WeightInfo for WeightInfo<T> {
	/// Storage: `XcmWeightTrader::SupportedAssets` (r:1 w:1)
	/// Proof: `XcmWeightTrader::SupportedAssets` (`max_values`: None, `max_size`: Some(635), added: 3110, mode: `MaxEncodedLen`)
	fn add_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `4100`
		// Minimum execution time: 13_153_000 picoseconds.
		Weight::from_parts(13_611_000, 0)
			.saturating_add(Weight::from_parts(0, 4100))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `XcmWeightTrader::SupportedAssets` (r:1 w:1)
	/// Proof: `XcmWeightTrader::SupportedAssets` (`max_values`: None, `max_size`: Some(635), added: 3110, mode: `MaxEncodedLen`)
	fn edit_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `102`
		//  Estimated: `4100`
		// Minimum execution time: 14_633_000 picoseconds.
		Weight::from_parts(14_875_000, 0)
			.saturating_add(Weight::from_parts(0, 4100))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `XcmWeightTrader::SupportedAssets` (r:1 w:1)
	/// Proof: `XcmWeightTrader::SupportedAssets` (`max_values`: None, `max_size`: Some(635), added: 3110, mode: `MaxEncodedLen`)
	fn resume_asset_support() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `102`
		//  Estimated: `4100`
		// Minimum execution time: 14_357_000 picoseconds.
		Weight::from_parts(14_758_000, 0)
			.saturating_add(Weight::from_parts(0, 4100))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `XcmWeightTrader::SupportedAssets` (r:1 w:1)
	/// Proof: `XcmWeightTrader::SupportedAssets` (`max_values`: None, `max_size`: Some(635), added: 3110, mode: `MaxEncodedLen`)
	fn pause_asset_support() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `102`
		//  Estimated: `4100`
		// Minimum execution time: 14_473_000 picoseconds.
		Weight::from_parts(14_840_000, 0)
			.saturating_add(Weight::from_parts(0, 4100))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `XcmWeightTrader::SupportedAssets` (r:1 w:1)
	/// Proof: `XcmWeightTrader::SupportedAssets` (`max_values`: None, `max_size`: Some(635), added: 3110, mode: `MaxEncodedLen`)
	fn remove_asset() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `102`
		//  Estimated: `4100`
		// Minimum execution time: 13_942_000 picoseconds.
		Weight::from_parts(14_378_000, 0)
			.saturating_add(Weight::from_parts(0, 4100))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
